name: CI

on:
  pull_request:
  push:
    branches:
      - deploy-staging
      - deploy-prod

jobs:
  lint_test:
    name: 🚴 Lint + Test 🚴
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 🤞 Run Lint 🧪
        run: pnpm lint

      - name: 🤞 Run Lint 🧪
        run: pnpm lint:css

      - name: 🤞 Run Test 🧪
        run: pnpm test

  check_build:
    name: 🚴 Check Build 🚴
    needs: lint_test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 🤞 Run Build 🧪
        uses: ./.github/actions/run_build
        with:
          BUILD_OUTPUT_DIR: build-dev/
          UPLOAD_ARTIFACT_NAME: helix-dev
          REACT_APP_ENV: "dev"
          REACT_APP_MAPBOX_ACCESS_TOKEN: ${{ secrets.REACT_APP_MAPBOX_ACCESS_TOKEN }}
          REACT_APP_SENTRY_DSN: ${{ secrets.REACT_APP_SENTRY_DSN }}
          REACT_APP_HCATPCHA_SITEKEY: ${{ secrets.REACT_APP_HCATPCHA_SITEKEY }}
          REACT_APP_HELIX_CONTACT_PERSON: ${{ secrets.REACT_APP_HELIX_CONTACT_PERSON }}

  run_build:
    name: 🚴 Build 🚴
    needs: lint_test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 🤞 Run Build 🧪 (Helix-STAGING)
        uses: ./.github/actions/run_build
        if: github.ref == 'refs/heads/deploy-staging'
        with:
          BUILD_OUTPUT_DIR: build-staging/
          UPLOAD_ARTIFACT_NAME: helix-staging
          REACT_APP_ENV: "staging"
          REACT_APP_MAPBOX_ACCESS_TOKEN: ${{ secrets.REACT_APP_MAPBOX_ACCESS_TOKEN }}
          REACT_APP_SENTRY_DSN: ${{ secrets.REACT_APP_SENTRY_DSN }}
          REACT_APP_HCATPCHA_SITEKEY: ${{ secrets.REACT_APP_HCATPCHA_SITEKEY }}
          REACT_APP_HELIX_CONTACT_PERSON: ${{ secrets.REACT_APP_HELIX_CONTACT_PERSON }}
          # Overwrite
          REACT_APP_GRAPHQL_ENDPOINT: "https://helix-tools-api-staging.idmcdb.org/graphql"
          REACT_APP_GRAPHIQL_ENDPOINT: "https://helix-tools-api-staging.idmcdb.org/graphiql"
          REACT_APP_SWAGGER_ENDPOINT:  "https://helix-tools-api-staging.idmcdb.org/external-api/"

      - name: 🤞 Run Build 🧪 (Helix-PROD)
        if: github.ref == 'refs/heads/deploy-prod'
        uses: ./.github/actions/run_build
        with:
          BUILD_OUTPUT_DIR: build-prod/
          UPLOAD_ARTIFACT_NAME: helix-prod
          REACT_APP_ENV: "prod"
          REACT_APP_MAPBOX_ACCESS_TOKEN: ${{ secrets.REACT_APP_MAPBOX_ACCESS_TOKEN }}
          REACT_APP_SENTRY_DSN: ${{ secrets.REACT_APP_SENTRY_DSN }}
          REACT_APP_HCATPCHA_SITEKEY: ${{ secrets.REACT_APP_HCATPCHA_SITEKEY }}
          REACT_APP_HELIX_CONTACT_PERSON: ${{ secrets.REACT_APP_HELIX_CONTACT_PERSON }}

  helix_staging_deploy:
    name: HELIX-STAGING
    if: github.ref == 'refs/heads/deploy-staging'
    needs: run_build
    uses: ./.github/workflows/aws_deploy.yml
    secrets: inherit
    with:
      GH_ENVIRONMENT_NAME: staging
      GH_ENVIRONMENT_URL: https://helix.staging.tools.idmcdb.org
      ARTIFACT_NAME: helix-staging

  helix_prod_deploy:
    name: HELIX-PROD
    if: github.ref == 'refs/heads/deploy-prod'
    needs: run_build
    uses: ./.github/workflows/aws_deploy.yml
    secrets: inherit
    with:
      GH_ENVIRONMENT_NAME: prod
      GH_ENVIRONMENT_URL: https://helix.tools.idmcdb.org
      ARTIFACT_NAME: helix-prod
